name: CI

on:
  push:
  pull_request:

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: requirements.txt

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Belt & suspenders to avoid the httpx miss:
          pip install httpx==0.28.1

      - name: Run tests
        run: pytest -q

      - name: Build Docker image
        run: docker build -t day1-fastapi .
