name: CI

on:
  push:
  pull_request:

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}   # <-- ensure 'app' is importable
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: requirements.txt

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install httpx==0.28.1

      - name: Sanity check paths
        run: |
          pwd
          ls -la
          python - <<'PY'
import sys, os
print("WORKSPACE:", os.getcwd())
print("PYTHONPATH:", os.environ.get("PYTHONPATH"))
print("sys.path[0]:", sys.path[0])
print("repo has 'app'? ->", os.path.isdir("app"), os.listdir("app") if os.path.isdir("app") else "no app/")
PY

      - name: Run tests
        run: pytest -q

      - name: Build Docker image
        run: docker build -t day1-fastapi .
